# Generated by Django 4.2.11 on 2025-05-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=20)),
                ('EEPROM_description', models.TextField()),
                ('part_identification_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('MLX90614_adress', models.CharField(max_length=6)),
                ('RFID_adress', models.CharField(max_length=6)),
                ('station_identification_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('time', models.TimeField()),
                ('Date', models.DateField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parts')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station')),
            ],
        ),
    ]
